# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: fedora-cinnamon-nvidia-extras

description: Custom immutable Fedora Cinnamon image with NVIDIA/CUDA, development tools, VMs, and more.

base-image: ghcr.io/ublue-os/base-nvidia
image-version: 42

modules:
  - type: bling
    install:
      - negativo17
  - type: dnf
    repos:
      files:
        - https://src.fedoraproject.org/rpms/fedora-repos/raw/f42/f/fedora-cisco-openh264.repo
      copr:
        - atim/starship
      #nonfree: negativo17
    install:
      allow-erasing: true
      packages:
        #- gdm
        - xorg-x11-server-Xorg
        - xorg-x11-nvidia
        - cuda-devel
        - cinnamon-session

        - gnome-shell-extension-gsconnect

        # Virtualization Tools
        - virt-manager # Virtual Machine Manager GUI
        - libvirt # Virtualization library and daemon
        - virt-install # Command line tool for installing VMs

        # Alternative Terminal and Text Editor
        - ptyxis # Second terminal emulator
        - geany # Second lightweight text editor
        - starship
        - conda

        # Multimedia Codecs and Thumbnail Generators
        - ffmpeg
        - gstreamer1
        - gstreamer1-plugin-libav # FFmpeg plugin for GStreamer
        - libvkd3d
        # - intel-media-driver # Intel Media Driver for VAAPI (if you have Intel iGPU)

        - openh264 # Cisco OpenH264 codec

        # Thumbnailers
        - ffmpegthumbnailer
        - gnome-directory-thumbnailer
        - gnome-kra-ora-thumbnailer
        - tumbler

        # Packages for working with Apple Devices
        - usbmuxd
        - libimobiledevice-utils
        - ifuse 

        - android-tools

        # Extensive Development Extras
        - make
        - gcc
        - git
        - cmake
        - htop
        - nano
        - gdb
        - valgrind
        - strace
        - ltrace
        - pkgconf-pkg-config
        - zlib-devel
        - bzip2-devel
        - xz-devel
        - openssl-devel
        - elfutils-libelf-devel
        - libffi-devel
        - readline-devel
        - ncurses-devel
        - usbutils
        - lshw
        - pciutils
        - ddrescue

    remove:
      packages:
        - mesa-libGL
        - mesa-dri-drivers
        - noopenh264
        - thunderbird
        - hexchat
        - mpv
        #- slick-greeter
        #- slick-greeter-cinnamon
        #- lightdm

    group-install:
      with-optional: false # install optional packages from group
      packages:
        - cinnamon-desktop

  - type: files
    files:
    #  - source: system
    #    destination: /
    - source: apply-firstboot-kargs.sh
      destination: /etc/apply-firstboot-kargs.sh
    - source: apply-firstboot-kargs.service
      destination: /etc/systemd/system/apply-firstboot-kargs.service
    #- source: config.conf
    #  destination: /etc/gdm/config.conf
    - source: cinnamon.desktop
      destination: /usr/share/xsessions/cinnamons.desktop

  #- type: script
  #  snippets:
  #    - "chmod +x /usr/local/bin/apply-firstboot-kargs.sh"

  - type: systemd
    system:
      enabled:
        #- gdm.service
        - libvirtd.service

        - apply-firstboot-kargs.service

  - type: default-flatpaks
    system:
      install:
        - org.videolan.VLC
        - org.mozilla.firefox
        - org.chromium.Chromium
        - com.github.tchx84.Flatseal
        - org.fedoraproject.MediaWriter
    user:
      install:
        - com.usebottles.bottles

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly



#- https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
#- https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
#- https://negativo17.org/repos/fedora-nvidia.repo
#- https://negativo17.org/repos/fedora-multimedia.repo
#- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-42/atim-starship-fedora-42.repo